-- SQL Script to set up allowed wallets database table in Supabase
-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor > New Query)

-- 1. Create the whitelist table
CREATE TABLE IF NOT EXISTS allowed_wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_address TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
-- This ensures the table is protected and accessible exactly as configured
ALTER TABLE allowed_wallets ENABLE ROW LEVEL SECURITY;

-- 3. Create a Policy to allow public SELECT (read) access
-- This is secure because anyone can verify if an EVM address is in the database,
-- but only database administrators can write (INSERT, UPDATE, DELETE) entries.
CREATE POLICY "Allow public read access to allowed_wallets" 
ON allowed_wallets 
FOR SELECT 
USING (true);

-- 4. Insert sample EVM wallet addresses for testing
-- IMPORTANT: Make sure wallet addresses are stored in LOWERCASE for exact matching
INSERT INTO allowed_wallets (wallet_address) VALUES 
('0x7e128cb5fe09a045c2109a2b345c90d56e299f81'), -- Sample 1
('0x5c90c7d11ab88a4ca1b88e12c1015f81791f8a4c'), -- Sample 2
('0x0e5511aa7b770c458b770c459d9a99ff5e29a3a1'); -- Sample 3

-- Note: To whitelist your own wallet for testing, run:
-- INSERT INTO allowed_wallets (wallet_address) VALUES ('your_address_here_in_lowercase');
