-- SQL Script to set up the gacha_claims database table in Supabase
-- Run this in your Supabase SQL Editor (Dashboard > SQL Editor > New Query)

-- 1. Create the gacha_claims table
CREATE TABLE IF NOT EXISTS gacha_claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address TEXT UNIQUE NOT NULL, -- Unique constraint prevents multiple draws from the same IP
    wallet_address TEXT NOT NULL,
    claimed_code TEXT NOT NULL,
    reward_type TEXT NOT NULL CHECK (reward_type IN ('gtd', 'fcfs', 'failure')),
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE gacha_claims ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies
-- Allow anyone (public anon client) to select/read claims (required for checking if IP is already registered)
CREATE POLICY "Allow public read access to gacha_claims" 
ON gacha_claims 
FOR SELECT 
TO anon 
USING (true);

-- Allow anyone (public anon client) to insert their claim (required to submit gacha results)
CREATE POLICY "Allow public insert access to gacha_claims" 
ON gacha_claims 
FOR INSERT 
TO anon 
WITH CHECK (true);
