-- SQL Query to create allowed_wallets table and enable RLS policies
-- Run this in your Supabase SQL Editor

-- Create table for whitelisted wallets
CREATE TABLE IF NOT EXISTS allowed_wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_address TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE allowed_wallets ENABLE ROW LEVEL SECURITY;

-- Create Policy to allow public SELECT (read) access
DROP POLICY IF EXISTS "Allow public read access to allowed_wallets" ON allowed_wallets;
CREATE POLICY "Allow public read access to allowed_wallets" 
ON allowed_wallets 
FOR SELECT 
USING (true);
